application:
  title: Notify Gateway
  consume: true
  queue:
    new: testQueue.fifo

springfox:
  documentation:
    swagger:
      v2:
        path: /v1/swagger-docs
        
# Note these are default values that will be overriden by aws secrets manager values 
notify-api-key-dev:
notify-api-key-team: