application:
  title: Notify Gateway
  message-batch-rate: 10
  message-group-id-payments: PAYMENTS_RECEIPT

job:
  notify-gateway:
    new-queue-url: notify-gateway_new_dev.fifo
    request-limit-queue-url: notify-gateway_request_limit_dev.fifo
    service-down-queue-url: notify-gateway_service_down_dev.fifo
    service-error-queue-url: notify-gateway_service_error_dev.fifo
    dlq-url: notify-gateway_dlq_dev.fifo

springfox:
  documentation:
    swagger:
      v2:
        path: /v1/swagger-docs
        
# Note this is a default value that will be overridden by aws secrets manager values 
notify-api-key: test